[package]
name = "clifford-qubit"
version = "0.1.0"
edition = "2024"
authors = ["Michael Nelson <absoludity@gmail.com>"]
description = ""
license = "MIT OR Apache-2.0"
keywords = ["clifford", "qubit"]

[dependencies]
clifford-3-even = "0.1.1"
num = "0.4.1"

[dev-dependencies]
rstest = "0.18.2"
